const express=require('express')
const router=express.Router()
const adminContoller=require("../controllers/adminController")
const ifLoggedIn=require("../middleware/ifLoggedIn")
const ifNotLoggedIn=require("../middleware/ifNotLoggedIn")
const ifAdmin=require("../middleware/ifAdmin")
const RootController = require('../controllers/rootController')


// router.get('/login', ifLoggedIn, adminContoller.loginPage)
// router.get('/', adminContoller.home)
// router.get('/signup', ifLoggedIn,adminContoller.signupPage)
// router.get('/addHR',ifNotLoggedIn, ifAdmin, adminContoller.addHRPage)
// router.get('/login', adminContoller.loginPage)
// router.get('/dashboard', adminContoller.dashboard)
// router.get('/logout',ifNotLoggedIn, ifAdmin, RootController.logout)
router.get('/signup',ifLoggedIn,adminContoller.signupPage)
router.get('/', ifNotLoggedIn,  ifAdmin, adminContoller.home)
router.get('/addHR',ifNotLoggedIn, ifAdmin, adminContoller.addHRPage)
router.get('/jupitorLeaves', ifNotLoggedIn, ifAdmin, adminContoller.viewLeaves)
router.get('/editLeave/:paygrade_level',ifNotLoggedIn, ifAdmin, adminContoller.editLeavePage)
router.get('/jupitorBranches',ifNotLoggedIn, ifAdmin, adminContoller.viewBranches);
router.get('/editBranch/:branch_name',ifNotLoggedIn, ifAdmin, adminContoller.editBranchPage)
router.get('/addCustomAttribute',ifNotLoggedIn, ifAdmin, adminContoller.addCustomAttributePage)
router.get('/viewCustomAttributes',ifNotLoggedIn, ifAdmin, adminContoller.viewCustomAttributes)
router.get('/deleteCustomAttribute/:columnName',ifNotLoggedIn, ifAdmin, adminContoller.deleteCustomAttribute)
router.get('/jupitorPayGrades',ifNotLoggedIn, ifAdmin, adminContoller.payGradePage)
router.get('/editPaygrade/:paygrade_level',ifNotLoggedIn, ifAdmin, adminContoller.editPayGradePage)
router.get('/jupitorEmployeeStatus',ifNotLoggedIn, ifAdmin, adminContoller.employeeStatusPage)
router.get('/editEmployeeStatus/:EmployeeStatus',ifNotLoggedIn, ifAdmin, adminContoller.editEmployeeStatusPage)
router.get('/editJobType/:jobType',ifNotLoggedIn, ifAdmin, adminContoller.editJobTypePage)
router.get('/jupitorJobs',ifNotLoggedIn, ifAdmin, adminContoller.jobTypePage)
router.get('/branch/:branch',ifNotLoggedIn, ifAdmin, adminContoller.getBranch)
router.get('/adminProfile',ifNotLoggedIn, ifAdmin, adminContoller.adminProfilePage)
router.get('/jupitorDepartments',ifNotLoggedIn, ifAdmin, adminContoller.viewDepartments)
router.get('/changePassword',ifNotLoggedIn, ifAdmin, adminContoller.changePasswordPage)




router.post('/addHR',ifNotLoggedIn,  ifAdmin, adminContoller.addHR)
router.post('/changePassword/:uid',ifNotLoggedIn, ifAdmin, adminContoller.changePassword)
router.post('/addBranch',ifNotLoggedIn, ifAdmin, adminContoller.addBranch)
router.post('/editBranch/:branch_name',ifNotLoggedIn, ifAdmin, adminContoller.editBranch)
router.post('/editLeave/:paygrade_level',ifNotLoggedIn, ifAdmin, adminContoller.editLeave)
router.post('/addCustomAttribute',ifNotLoggedIn, ifAdmin, adminContoller.addCustomAttribute)
router.post('/addPayGrade',ifNotLoggedIn, ifAdmin, adminContoller.addPayGrade)
router.post('/editPaygrade/:paygrade_level',ifNotLoggedIn, ifAdmin, adminContoller.editPayGrade)
router.post('/addEmployeeStatus',ifNotLoggedIn, ifAdmin, adminContoller.addEmployeeStatus)
router.post('/editEmployeeStatus/:EmployeeStatus',ifNotLoggedIn, ifAdmin, adminContoller.editEmployeeStatus)
router.post('/addJobType',ifNotLoggedIn, ifAdmin, adminContoller.addJobType)
router.post('/editJobType/:jobType',ifNotLoggedIn, ifAdmin, adminContoller.editJobType)
router.post('/addDepartment',ifNotLoggedIn, ifAdmin, adminContoller.addDepartment)
router.post('/signup', ifLoggedIn, adminContoller.signup)

// router.post('/login',ifLoggedIn, adminContoller.login)
// router.post('/addHR', ifNotLoggedIn, ifAdmin, adminContoller.addHR)
// router.post('/signup', ifLoggedIn, adminContoller.signup)


module.exports=router